#--- 基础设置 ---
set -g default-terminal "screen-256color"
set -g mouse on               # 开启鼠标支持（点击切换面板、滚轮滚动）
set -g base-index 1           # 窗口编号从1开始
setw -g pane-base-index 1     # 面板编号从1开始
set -g renumber-windows on    # 关闭窗口后重新编号
# --- 快捷键修改 ---
# 将前缀键从 Ctrl-b 改为 Ctrl-a (更方便单手操作)
#set -g prefix C-a
#unbind C-b
#bind C-a send-prefix
set -g prefix C-b
bind - split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
# 绑定 Prefix + H/J/K/L 来调整面板大小
# -r 表示可重复 (repeatable)，在 500ms 内连续按键有效
bind -r H resize-pane -L 5   # 向左扩大 5 格
bind -r J resize-pane -D 5   # 向下扩大 5 格
bind -r K resize-pane -U 5   # 向上扩大 5 格
bind -r L resize-pane -R 5   # 向右扩大 5 格

# 绑定 Prefix + r 重新加载配置，并显示提示消息
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
# 左右切换 (J 和 K)

# --- 插件列表 ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'                # 漂亮的主题
set -g @plugin 'tmux-plugins/tmux-resurrect' # 会话手动保存
set -g @plugin 'tmux-plugins/tmux-continuum' # 会话自动保存
set -g @plugin 'tmux-plugins/tmux-yank'      # 复制到系统剪贴板
set -g @plugin 'sainnhe/tmux-fzf'            # 文件查找fzf
set -g @plugin 'jaclu/tmux-menus'            # menu for command prompt line
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# --- 插件配置 ---
set -g @continuum-restore 'on'               # 启动 tmux 时自动恢复上一次会话
set -g @dracula-show-powerline true          # 启用 Dracula 状态栏美化
set -g @dracula-plugins "cpu-usage ram-usage time" # 状态栏显示内容
set -g @dracula-military-time true
set -g @plugin 'christoomey/vim-tmux-navigator'


# 初始化 TPM (这行必须放在文件最底部)
run '~/.tmux/plugins/tpm/tpm'

